name: bpoe-here-strings
on:
  pull_request:
    paths:
      - "**/*.ps1"
      - "**/*.psm1"
      - "**/*.md"
  workflow_dispatch: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PowerShell lint — here-strings/Prompts
        shell: pwsh
        run: pwsh -NoProfile -File tools/BPOE/Lint-HereStrings.ps1 -Root .